---
- name: Change Cisco Router Hostname
  hosts: all
  gather_facts: false

  vars:
    new_hostname: "{{ new_hostname }}"

  tasks:
    - name: Configure hostname
      ansible.netcommon.cli_config:
        config: |
          hostname {{ new_hostname }}

    - name: Save running config
      ansible.netcommon.cli_command:
        command: write memory
