---
- name: Change Cisco Router Hostname
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Ensure new_hostname is provided
      ansible.builtin.assert:
        that:
          - new_hostname is defined
          - new_hostname | length > 0
        fail_msg: "You must pass new_hostname (e.g., in AWX Extra Vars or a Survey)."

    - name: Configure hostname
      cisco.ios.ios_config:
        lines:
          - "hostname {{ new_hostname }}"

    - name: Save running-config to startup-config
      cisco.ios.ios_config:
        save_when: modified
