---
- name: Set hostnames from inventory
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Pre-check current hostname
      cisco.ios.ios_command:
        commands:
          - show run | i ^hostname
      register: pre
      changed_when: false

    - name: Configure hostname to match inventory name
      cisco.ios.ios_config:
        lines:
          - "hostname {{ inventory_hostname }}"

    - name: Save running-config to startup-config (only if modified)
      cisco.ios.ios_config:
        save_when: modified

    - name: Post-check hostname
      cisco.ios.ios_command:
        commands:
          - show run | i ^hostname
      register: post
      changed_when: false

    - name: Show before/after
      ansible.builtin.debug:
        msg:
          - "Before: {{ pre.stdout[0] | default('N/A') }}"
          - "After : {{ post.stdout[0] | default('N/A') }}"
